module.exports = (roll) => {
	if(roll <= 15) return "1 **+1 Weapon**\n";
	if(roll <= 18) return "1 **+1 Shield**\n";
	if(roll <= 21) return "1 **Sentinel Shield**\n";
	if(roll <= 23) return "1 **Amulet of Proof against Detection and Location**\n";
	if(roll <= 25) return "1 **Boots of Elvenkind**\n";
	if(roll <= 27) return "1 **Boots of Striding and Springing**\n";
	if(roll <= 29) return "1 **Bracers of Archery**\n";
	if(roll <= 31) return "1 **Brooch of Shielding**\n";
	if(roll <= 33) return "1 **Broom of Flying**\n";
	if(roll <= 35) return "1 **Cloak of Elvenkind**\n";
	if(roll <= 37) return "1 **Cloak of Protection**\n";
	if(roll <= 39) return "1 **Gauntlets of Ogre Power**\n";
	if(roll <= 41) return "1 **Hat of Disguise**\n";
	if(roll <= 43) return "1 **Javelin of Lightning**\n";
	if(roll <= 45) return "1 **Pearl of Power**\n";
	if(roll <= 47) return "1 **+1 Rod of the Pact Keeper**\n";
	if(roll <= 49) return "1 **Slippers of Spider Climbing**\n";
	if(roll <= 51) return "1 **Staff of the Adder**\n";
	if(roll <= 53) return "1 **Staff of the Python**\n";
	if(roll <= 55) return "1 **Sword of Vengeance**\n";
	if(roll <= 57) return "1 **Trident of Fish Command**\n";
	if(roll <= 59) return "1 **Wand of Magic Missiles**\n";
	if(roll <= 61) return "1 **+1 Wand of the War Mage**\n";
	if(roll <= 63) return "1 **Wand of Web**\n";
	if(roll <= 65) return "1 **Weapon of Warning**\n";
	if(roll === 66) return "1 **Adamantine Armor (Chain Mail)**\n";
	if(roll === 67) return "1 **Adamantine Armor (Chain Shirt)**\n";
	if(roll === 68) return "1 **Adamantine Armor (Scale Mail)**\n";
	if(roll === 69) return "1 **Bag of Tricks (Gray)**\n";
	if(roll === 70) return "1 **Bag of Tricks (Rust)**\n";
	if(roll === 71) return "1 **Bag of Tricks (Tan)**\n";
	if(roll === 72) return "1 **Boots of the Winterlands**\n";
	if(roll === 73) return "1 **Circlet of Blasting**\n";
	if(roll === 74) return "1 **Deck of Illusions**\n";
	if(roll === 75) return "1 **Eversmoking Bottle**\n";
	if(roll === 76) return "1 **Eyes of Charming**\n";
	if(roll === 77) return "1 **Eyes of the Eagle**\n";
	if(roll === 78) return "1 **Figurine of Wondrous Power (Silver Raven)**\n";
	if(roll === 79) return "1 **Gem of Brightness**\n";
	if(roll === 80) return "1 **Gloves of Missile Snaring**\n";
	if(roll === 81) return "1 **Gloves of Swimming and Climbing**\n";
	if(roll === 82) return "1 **Gloves of Thievery**\n";
	if(roll === 83) return "1 **Headband of Intellect**\n";
	if(roll === 84) return "1 **Helm of Telepathy**\n";
	if(roll === 85) return "1 **Instrument of the Bards (Doss Lute)**\n";
	if(roll === 86) return "1 **Instrument of the Bards (Fochlucan Bandore)**\n";
	if(roll === 87) return "1 **Instrument of the Bards (Mac-Fuimidh Cittern)**\n";
	if(roll === 88) return "1 **Medallion of Thoughts**\n";
	if(roll === 89) return "1 **Necklace of Adaptation**\n";
	if(roll === 90) return "1 **Periapt of Wound Closure**\n";
	if(roll === 91) return "1 **Pipes of Haunting**\n";
	if(roll === 92) return "1 **Pipes of the Sewers**\n";
	if(roll === 93) return "1 **Ring of Jumping**\n";
	if(roll === 94) return "1 **Ring of Mind Shielding**\n";
	if(roll === 95) return "1 **Ring of Warmth**\n";
	if(roll === 96) return "1 **Ring of Water Walking**\n";
	if(roll === 97) return "1 **Quiver of Ehlonna**\n";
	if(roll === 98) return "1 **Stone of Good Luck**\n";
	if(roll === 99) return "1 **Wind Fan**\n";
	if(roll === 100) return "1 **Winged Boots**\n";
};
