module.exports = (roll) => {
	if(roll <= 15) return "Potion of Superior Healing";
	if(roll <= 22) return "Spell Scroll (4th level)";
	if(roll <= 27) return "Ammunition +2";
	if(roll <= 32) return "Potion of Clairvoyance";
	if(roll <= 37) return "Potion of Diminution";
	if(roll <= 42) return "Potion of Gaseous Form";
	if(roll <= 47) return "Potion of Frost Giant Strength";
	if(roll <= 52) return "Potion of Stone Giant Strength";
	if(roll <= 57) return "Potion of Heroism";
	if(roll <= 62) return "Potion of Invulnerability";
	if(roll <= 67) return "Potion of Mind Reading";
	if(roll <= 72) return "Spell Scroll (5th level)";
	if(roll <= 75) return "Elixir of Health";
	if(roll <= 78) return "Oil of Etherealness";
	if(roll <= 81) return "Potion of Fire Gaitn Strength";
	if(roll <= 84) return "Quaal's Feather Token";
	if(roll <= 87) return "Scroll of Protection";
	if(roll <= 89) return "Bag of Beans";
	if(roll <= 91) return "Bead of Force";
	if(roll === 92)	return "Chime of Opening";
	if(roll === 93)	return "Decanter of Endless Water";
	if(roll === 94)	return "Eyes of Minute Seeing";
	if(roll === 95) return "Foldiong Boat";
	if(roll === 96) return "Hewards Handy Haversack";
	if(roll === 97) return "Horseshoes of speed";
	if(roll === 98) return "Necklace of Fireballs";
	if(roll === 99) return "Periapt of Health";
	if(roll === 100) return "Sending Stones";
};
