module.exports = () => {
	return [
		{ "roll": 15, "name": "**Potion of Superior Healing**", "link":"https://www.dndbeyond.com/magic-items/potion-of-healing" },
		{ "roll": 22, "name": "**Spell Scroll (4th level)**", "link":"https://www.dndbeyond.com/magic-items/spell-scroll" },
		{ "roll": 27, "name": "**+2 Ammunition**", "link":"https://www.dndbeyond.com/magic-items/ammunition-2" },
		{ "roll": 32, "name": "**Potion of Clairvoyance**", "link":"https://www.dndbeyond.com/magic-items/potion-of-clairvoyance" },
		{ "roll": 37, "name": "**Potion of Diminution**", "link":"https://www.dndbeyond.com/magic-items/potion-of-diminution" },
		{ "roll": 42, "name": "**Potion of Gaseous Form**", "link":"https://www.dndbeyond.com/magic-items/potion-of-gaseous-form" },
		{ "roll": 47, "name": "**Potion of Frost Giant Strength**", "link":"https://www.dndbeyond.com/magic-items/potion-of-giant-strength" },
		{ "roll": 52, "name": "**Potion of Stone Giant Strength**", "link":"https://www.dndbeyond.com/magic-items/potion-of-giant-strength" },
		{ "roll": 57, "name": "**Potion of Heroism**", "link":"https://www.dndbeyond.com/magic-items/potion-of-heroism" },
		{ "roll": 62, "name": "**Potion of Invulnerability**", "link":"https://aversten.obsidianportal.com/wiki_pages/potion-of-invulnerability" },
		{ "roll": 67, "name": "**Potion of Mind Reading**", "link":"https://www.dndbeyond.com/magic-items/potion-of-mind-reading" },
		{ "roll": 72, "name": "**Spell Scroll (5th level)**", "link":"https://www.dndbeyond.com/magic-items/spell-scroll" },
		{ "roll": 75, "name": "**Elixir of Health**", "link":"https://aversten.obsidianportal.com/wiki_pages/elixir-of-health" },
		{ "roll": 78, "name": "**Oil of Etherealness**", "link":"https://www.dndbeyond.com/magic-items/oil-of-etherealness" },
		{ "roll": 81, "name": "**Potion of Fire Giant Strength**", "link":"https://www.dndbeyond.com/magic-items/potion-of-giant-strength" },
		{ "roll": 84, "name": "**Quaal's Feather Token**", "link":"https://aversten.obsidianportal.com/wiki_pages/quaals-feather-token" },
		{ "roll": 87, "name": "**Scroll of Protection**", "link":"https://aversten.obsidianportal.com/wiki_pages/scroll-of-protection" },
		{ "roll": 89, "name": "**Bag of Beans**", "link":"https://www.dndbeyond.com/magic-items/bag-of-beans" },
		{ "roll": 91, "name": "**Bead of Force**", "link":"https://www.dndbeyond.com/magic-items/bead-of-force" },
		{ "roll": 92, "name": "**Chime of Opening**", "link":"https://www.dndbeyond.com/magic-items/chime-of-opening" },
		{ "roll": 93, "name": "**Decanter of Endless Water**", "link":"https://www.dndbeyond.com/magic-items/decanter-of-endless-water" },
		{ "roll": 94, "name": "**Eyes of Minute Seeing**", "link":"https://www.dndbeyond.com/magic-items/eyes-of-minute-seeing" },
		{ "roll": 95, "name": "**Folding Boat**", "link":"https://www.dndbeyond.com/magic-items/folding-boat" },
		{ "roll": 96, "name": "**Hewards Handy Haversack**", "link":"https://aversten.obsidianportal.com/wikis/hewards-handy-haversack" },
		{ "roll": 97, "name": "**Horseshoes of speed**", "link":"https://www.dndbeyond.com/magic-items/horseshoes-of-speed" },
		{ "roll": 98, "name": "**Necklace of Fireballs**", "link":"https://www.dndbeyond.com/magic-items/necklace-of-fireballs" },
		{ "roll": 99, "name": "**Periapt of Health**", "link":"https://www.dndbeyond.com/magic-items/periapt-of-health" },
		{ "roll": 100, "name": "**Sending Stones**", "link":"https://aversten.obsidianportal.com/wiki_pages/sending-stones" }
	];
};
