module.exports = (roll) => {
	if(roll <= 10) return { name:"**+3 Weapon**", link:"https://www.dndbeyond.com/magic-items/weapon-3" };
	if(roll <= 12) return { name:"**Amulet of the Planes**", link:"https://www.dndbeyond.com/magic-items/amulet-of-the-planes" };
	if(roll <= 14) return { name:"**Carpet of Flying**", link:"https://www.dndbeyond.com/magic-items/carpet-of-flying" };
	if(roll <= 16) return { name:"**Crystal Ball (Very Rare Version)**", link:"https://www.dndbeyond.com/magic-items/crystal-ball" };
	if(roll <= 18) return { name:"**Ring of Regeneration**", link:"https://www.dndbeyond.com/magic-items/ring-of-regeneration" };
	if(roll <= 20) return { name:"**Ring of Shooting Stars**", link:"https://www.dndbeyond.com/magic-items/ring-of-shooting-stars" };
	if(roll <= 22) return { name:"**Ring Telekinesis**", link:"https://www.dndbeyond.com/magic-items/ring-of-telekinesis" };
	if(roll <= 24) return { name:"**Robe of Scintillating Colors**", link:"https://www.dndbeyond.com/magic-items/robe-of-scintillating-colors" };
	if(roll <= 26) return { name:"**Robe of Stars**", link:"https://www.dndbeyond.com/magic-items/robe-of-stars" };
	if(roll <= 28) return { name:"**Rod of Absorption**", link:"https://www.dndbeyond.com/magic-items/rod-of-absorption" };
	if(roll <= 30) return { name:"**Rod of Alertness**", link:"https://www.dndbeyond.com/magic-items/rod-of-alertness" };
	if(roll <= 32) return { name:"**Rod of Security**", link:"https://www.dndbeyond.com/magic-items/rod-of-security" };
	if(roll <= 34) return { name:"**+3 Rod of the Pact Keeper**", link:"https://aversten.obsidianportal.com/wiki_pages/rod-of-the-pact-keeper" };
	if(roll <= 36) return { name:"**Scimitar of Speed**", link:"https://www.dndbeyond.com/magic-items/scimitar-of-speed" };
	if(roll <= 38) return { name:"**+3 Shield**", link:"https://www.dndbeyond.com/magic-items/shield-3" };
	if(roll <= 40) return { name:"**Staff of Fire**", link:"https://www.dndbeyond.com/magic-items/staff-of-fire" };
	if(roll <= 42) return { name:"**Staff of Frost**", link:"https://www.dndbeyond.com/magic-items/staff-of-frost" };
	if(roll <= 44) return { name:"**Staff of Power**", link:"https://www.dndbeyond.com/magic-items/staff-of-power" };
	if(roll <= 46) return { name:"**Staff of Striking**", link:"https://www.dndbeyond.com/magic-items/staff-of-striking" };
	if(roll <= 48) return { name:"**Staff of Thunder and Lightning**", link:"https://www.dndbeyond.com/magic-items/staff-of-thunder-and-lightning" };
	if(roll <= 52) return { name:"**Sword of Sharpness**", link:"https://www.dndbeyond.com/magic-items/sword-of-sharpness" };
	if(roll <= 54) return { name:"**Wand of Polymorph**", link:"https://www.dndbeyond.com/magic-items/wand-of-polymorph" };
	if(roll === 55)	return { name:"**+3 Wand of the War Mage**", link:"https://www.dndbeyond.com/magic-items/wand-of-the-war-mage" };
	if(roll === 56)	return { name:"**Adamantine Armor (Half Plate)**", link:"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(roll === 57)	return { name:"**Adamantine Armor (Plate)**", link:"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(roll === 58)	return { name:"**Animated Shield**", link:"https://www.dndbeyond.com/magic-items/animated-shield" };
	if(roll === 59)	return { name:"**Belt of Fire Giant Strength**", link:"https://www.dndbeyond.com/magic-items/belt-of-fire-giant-strength" };
	if(roll === 60)	return { name:"**Armor, +1 Breastplate**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 61)	return { name:"**Armor of Resistance (Breastplate)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 62)	return { name:"**Candle of Invocation**", link:"https://www.dndbeyond.com/magic-items/candle-of-invocation" };
	if(roll === 63)	return { name:"**Armor, +2 Chain Mail**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll === 64)	return { name:"**Armor, +2 Chain Shirt**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll === 65)	return { name:"**Cloak of Arachnida**", link:"https://www.dndbeyond.com/magic-items/cloak-of-arachnida" };
	if(roll === 66)	return { name:"**Dancing Sword**", link:"https://www.dndbeyond.com/magic-items/dancing-sword" };
	if(roll === 67)	return { name:"**Demon Armor**", link:"https://www.dndbeyond.com/magic-items/demon-armor" };
	if(roll === 68)	return { name:"**Dragon Scale Mail**", link:"https://www.dndbeyond.com/magic-items/dragon-scale-mail" };
	if(roll === 69)	return { name:"**Dwarven Plate**", link:"https://www.dndbeyond.com/magic-items/dwarven-plate" };
	if(roll === 70)	return { name:"**Dwarven Thrower**", link:"https://www.dndbeyond.com/magic-items/dwarven-thrower" };
	if(roll === 71)	return { name:"**Efreeti Bottle**", link:"https://www.dndbeyond.com/magic-items/efreeti-bottle" };
	if(roll === 72)	return { name:"**Figurine of Wondrous Power (Obsidian Steed)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-obsidian-steed" };
	if(roll === 73)	return { name:"**Frost Brand**", link:"https://www.dndbeyond.com/magic-items/frost-brand" };
	if(roll === 74)	return { name:"**Helm of Brilliance**", link:"https://www.dndbeyond.com/magic-items/helm-of-brilliance" };
	if(roll === 75)	return { name:"**Horn of Valhalla (Bronze)**", link:"https://www.dndbeyond.com/magic-items/horn-of-valhalla-bronze" };
	if(roll === 76)	return { name:"**Instrument of the Bards (Anstruth Harp)**", link:"https://aversten.obsidianportal.com/wiki_pages/instrument-of-the-bards" };
	if(roll === 77)	return { name:"**Ioun Stone (Absorption)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-absorption" };
	if(roll === 78)	return { name:"**Ioun Stone (Agility)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-agility" };
	if(roll === 79)	return { name:"**Ioun Stone (Fortitude)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-fortitude" };
	if(roll === 80)	return { name:"**Ioun Stone (Insight)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-insight" };
	if(roll === 81)	return { name:"**Ioun Stone (Intellect)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-intellect" };
	if(roll === 82)	return { name:"**Ioun Stone (Leadership)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-leadership" };
	if(roll === 83)	return { name:"**Ioun Stone (Strength)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-strength" };
	if(roll === 84) return { name:"**Armor, +2 Leather**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll === 85)	return { name:"**Manual of Bodily Health**", link:"https://www.dndbeyond.com/magic-items/manual-of-bodily-health" };
	if(roll === 86)	return { name:"**Manual of Gainful Exercise**", link:"https://www.dndbeyond.com/magic-items/manual-of-gainful-exercise" };
	if(roll === 87)	return { name:"**Manual of Golems**", link:"https://www.dndbeyond.com/magic-items/manual-of-golems" };
	if(roll === 88)	return { name:"**Manual of Quickness of Action**", link:"https://www.dndbeyond.com/magic-items/manual-of-quickness-of-action" };
	if(roll === 89)	return { name:"**Mirror of Life Trapping**", link:"https://www.dndbeyond.com/magic-items/mirror-of-life-trapping" };
	if(roll === 90) return { name:"**Nine Lives Stealer**", link:"https://www.dndbeyond.com/magic-items/nine-lives-stealer" };
	if(roll === 91)	return { name:"**Oathbow**", link:"https://www.dndbeyond.com/magic-items/oathbow" };
	if(roll === 92)	return { name:"**Armor, +2 Scale Mail**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll === 93)	return { name:"**Spellguard Shield**", link:"https://www.dndbeyond.com/magic-items/spellguard-shield" };
	if(roll === 94)	return { name:"**Armor, +1 Splint**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 95)	return { name:"**Armor of Resistance (Splint)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 96)	return { name:"**Armor, +1 Studded Leather**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 97)	return { name:"**Armor of Resistance (Studded Leather)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 98) return { name:"**Tome of Clear Thought**", link:"https://www.dndbeyond.com/magic-items/tome-of-clear-thought" };
	if(roll === 99) return { name:"**Tome of Leadership and Influence**", link:"https://www.dndbeyond.com/magic-items/tome-of-leadership-and-influence" };
	if(roll === 100) return { name:"**Tome of Understanding**", link:"https://www.dndbeyond.com/magic-items/tome-of-understanding" };
};
