module.exports = (roll) => {
	if(roll <= 15) return "Potion of Greater Healing";
	if(roll <= 22) return "Potion of Fire Breath";
	if(roll <= 29) return "Potion of Resistance";
	if(roll <= 34) return "Ammunition +1";
	if(roll <= 39) return "Potion of Animal Friendship";
	if(roll <= 44) return "Potion of Hill Giant Strength";
	if(roll <= 49) return "Potion of Growth";
	if(roll <= 54) return "Potion of Water Breathing";
	if(roll <= 59) return "Spell Scroll (2nd level)";
	if(roll <= 64) return "Spell Scroll (3rd level)";
	if(roll <= 67) return "Bag of Holding";
	if(roll <= 70) return "Keoghtom's Ointment";
	if(roll <= 73) return "Oil of Slipperiness";
	if(roll <= 75) return "Dust of Disappearance";
	if(roll <= 77) return "Dust of Dryness";
	if(roll <= 79) return "Dust of Sneezing and Choking";
	if(roll <= 81) return "Elemental Gem";
	if(roll <= 83) return "Philter of Love";
	if(roll === 84) return "Alchemy Jug";
	if(roll === 85) return "Cap of Water Breathing";
	if(roll === 86) return "Cloak of the Manta Ray";
	if(roll === 87) return "Driftglobe";
	if(roll === 88) return "Goggles of Night";
	if(roll === 89) return "Helm of Comprehending Languages";
	if(roll === 90) return "Immovable Rod";
	if(roll === 91) return "Lantern of Revealing";
	if(roll === 92) return "Mariner's Armor";
	if(roll === 93) return "Mithral Armor";
	if(roll === 94) return "Potion of Poison";
	if(roll === 95) return "Ring of Swimming";
	if(roll === 96) return "Robe of Useful Items";
	if(roll === 97) return "Rope of Climbing";
	if(roll === 98) return "Saddle of the Cavalier";
	if(roll === 99) return "Wand of Magic Detection";
	if(roll === 100) return "Wand of Secrets";
};
