module.exports = (roll) => {
	if(roll <= 11) return "1 **+2 Weapon**\n";
	if(roll <= 14){
		const figurine = d8();
		if(figurine === 1) return "1 **Figurine of Wondrous Power (Bronze Griffon)**\n";
		if(figurine === 2) return "1 **Figurine of Wondrous Power (Ebony Fly)**\n";
		if(figurine === 3) return "1 **Figurine of Wondrous Power (Golden Lions)**\n";
		if(figurine === 4) return "1 **Figurine of Wondrous Power (Ivory Goats)**\n";
		if(figurine === 5) return "1 **Figurine of Wondrous Power (Marble Elephant)**\n";
		if(figurine <= 7) return "1 **Figurine of Wondrous Power (Onyx Dog)**\n";
		if(figurine === 8) return "1 **Figurine of Wondrous Power (Serpentine Owl)**\n";
	}
	if(roll === 15)	return "1 **Adamantine Armor (Breastplate)**\n";
	if(roll === 16)	return "1 **Adamantine Armor (Splint)**\n";
	if(roll === 17)	return "1 **Amulet of Health**\n";
	if(roll === 18)	return "1 **Armor of Vulnerability**\n";
	if(roll === 19)	return "1 **Arrow Catching Shield**\n";
	if(roll === 20)	return "1 **Belt of Dwarvenkind**\n";
	if(roll === 21)	return "1 **Belt of Hill Giant Strength**\n";
	if(roll === 22)	return "1 **Beserker Axe**\n";
	if(roll === 23)	return "1 **Boots of Levitation**\n";
	if(roll === 24)	return "1 **Boots of Speed**\n";
	if(roll === 25)	return "1 **Bowl of Commanding Fire Elementals**\n";
	if(roll === 26)	return "1 **Bracers of Defence**\n";
	if(roll === 27)	return "1 **Brazier of Commanding Fire Elementals**\n";
	if(roll === 28)	return "1 **Cape of the Mountebank**\n";
	if(roll === 29)	return "1 **Censer of Controlling Air Elementals**\n";
	if(roll === 30)	return "1 **Armor, +1 Chain Mail**\n";
	if(roll === 31)	return "1 **Armor of Resistance (Chain Mail)**\n";
	if(roll === 32)	return "1 **Armor of Resistance (Chain Shirt)**\n";
	if(roll === 33)	return "1 **Armor, +1 Chain Shirt**\n";
	if(roll === 34)	return "1 **Cloak of Displacement**\n";
	if(roll === 35)	return "1 **Cloak of the Bat**\n";
	if(roll === 36)	return "1 **Cube of Force**\n";
	if(roll === 37)	return "1 **Daern's Instant Fortress**\n";
	if(roll === 38)	return "1 **Dagger of Venom**\n";
	if(roll === 39)	return "1 **Dimensional Shackles**\n";
	if(roll === 40)	return "1 **Dragon Slayer**\n";
	if(roll === 41)	return "1 **Elven Chain**\n";
	if(roll === 42)	return "1 **Flame Tongue**\n";
	if(roll === 43)	return "1 **Gem of Seeing**\n";
	if(roll === 44)	return "1 **Giant Slayer**\n";
	if(roll === 45)	return "1 **Clamoured Studded Leather**\n";
	if(roll === 46)	return "1 **Helm of Teleportation**\n";
	if(roll === 47)	return "1 **Horn of Blasting**\n";
	if(roll === 48)	return "1 **Horn of Valhalla (Silver or Brass)**\n";
	if(roll === 49)	return "1 **Instrument of the bards (Canaithmandolin)**\n";
	if(roll === 50)	return "1 **Instrument of the bards (Cii Lyre)**\n";
	if(roll === 51)	return "1 **Loun Stone (Awareness)**\n";
	if(roll === 52)	return "1 **Loun Stone (Protection)**\n";
	if(roll === 53)	return "1 **Loun Stone (Reserve)**\n";
	if(roll === 54)	return "1 **Loun Stone (Sustenance)**\n";
	if(roll === 55)	return "1 **Iron Bands of Bilarro**\n";
	if(roll === 56)	return "1 **Armor, +1 Leather**\n";
	if(roll === 57)	return "1 **Armor of Resistance (Leather)**\n";
	if(roll === 58)	return "1 **Mace of Disruption**\n";
	if(roll === 59)	return "1 **Mace of Smiting**\n";
	if(roll === 60)	return "1 **Mace of Terror**\n";
	if(roll === 61)	return "1 **Mantle of Spell Resistance**\n";
	if(roll === 62)	return "1 **Necklace of Prayer Beads**\n";
	if(roll === 63)	return "1 **Periapt of Proof against Poison**\n";
	if(roll === 64)	return "1 **Ring of Animal Influence**\n";
	if(roll === 65)	return "1 **Ring of Evasion**\n";
	if(roll === 66)	return "1 **Ring of Feather Falling**\n";
	if(roll === 67)	return "1 **Ring of Free Action**\n";
	if(roll === 68)	return "1 **Ring of Protection**\n";
	if(roll === 69)	return "1 **Ring of Resistance**\n";
	if(roll === 70)	return "1 **Ring of Spell Storing**\n";
	if(roll === 71)	return "1 **Ring of the Ram**\n";
	if(roll === 72)	return "1 **Ring of X-Ray Vision**\n";
	if(roll === 73)	return "1 **Robe of Eyes**\n";
	if(roll === 74)	return "1 **Rod of Rulership**\n";
	if(roll === 75)	return "1 **+2 Rod of the Pact Keeper**\n";
	if(roll === 76)	return "1 **Rope of Entanglement**\n";
	if(roll === 77)	return "1 **Armor, +1 Scale Mail**\n";
	if(roll === 78)	return "1 **Armor of Resistance (Scale Mail)**\n";
	if(roll === 79)	return "1 **+2 Shield**\n";
	if(roll === 80)	return "1 **Shield of Missile Attraction**\n";
	if(roll === 81)	return "1 **Staff of Charming**\n";
	if(roll === 82)	return "1 **Staff of Healing**\n";
	if(roll === 83)	return "1 **Staff of Swarming Insects**\n";
	if(roll === 84) return "1 **Staff of the Woodlands**\n";
	if(roll === 85)	return "1 **Staff of Withering**\n";
	if(roll === 86)	return "1 **Stone of Controlling Earth Elementals**\n";
	if(roll === 87)	return "1 **Sun Blade**\n";
	if(roll === 88)	return "1 **Sword of Life Stealing**\n";
	if(roll === 89)	return "1 **Sword of Wounding**\n";
	if(roll === 90) return "1 **Tentacle Rod**\n";
	if(roll === 91)	return "1 **Vicious Weapon**\n";
	if(roll === 92)	return "1 **Wand of Binding**\n";
	if(roll === 93)	return "1 **Wand of Enemy Detection**\n";
	if(roll === 94)	return "1 **Wand of Fear**\n";
	if(roll === 95)	return "1 **Wand of Fireballs**\n";
	if(roll === 96)	return "1 **Wand of Lightning Bolts**\n";
	if(roll === 97)	return "1 **Wand of Paralysis**\n";
	if(roll === 98) return "1 **+2 Wand of the War Mage**\n";
	if(roll === 99) return "1 **Wand of Wonder**\n";
	if(roll === 100) return "1 **Wings of Flying**\n";

};
