module.exports = (roll) => {
	if(roll <= 10) return "1 **+3 Weapon**\n";
	if(roll <= 12) return "1 **Amulet of the Planes**\n";
	if(roll <= 14) return "1 **Carpet of Flying**\n";
	if(roll <= 16) return "1 **Crystal Ball (Very Rare Version)**\n";
	if(roll <= 18) return "1 **Ring of Regeneration**\n";
	if(roll <= 20) return "1 **Ring of Shooting Stars**\n";
	if(roll <= 22) return "1 **Ring Telekinesis**\n";
	if(roll <= 24) return "1 **Robe of Scintillating  Colors**\n";
	if(roll <= 26) return "1 **Robe of Stars**\n";
	if(roll <= 28) return "1 **Rod of Absorption**\n";
	if(roll <= 30) return "1 **Rod of Alertness**\n";
	if(roll <= 32) return "1 **Rod of Security**\n";
	if(roll <= 34) return "1 **+3 Rod of the Pact Keeper**\n";
	if(roll <= 36) return "1 **Scimitar of Speed**\n";
	if(roll <= 38) return "1 **+3 Shield**\n";
	if(roll <= 40) return "1 **Staff of Fire**\n";
	if(roll <= 42) return "1 **Staff of Frost**\n";
	if(roll <= 44) return "1 **Staff of Power**\n";
	if(roll <= 46) return "1 **Staff of Striking**\n";
	if(roll <= 48) return "1 **Staff of Thunder and Lightning**\n";
	if(roll <= 52) return "1 **Sword of Sharpness**\n";
	if(roll <= 54) return "1 **Wand of Polymorph**\n";
	if(roll === 55)	return "1 **+3 Wand of the War Mage**\n";
	if(roll === 56)	return "1 **Adanabtube Arnor (Half Plate)**\n";
	if(roll === 57)	return "1 **Adamantine Armor (Plate)**\n";
	if(roll === 58)	return "1 **Animated Shield**\n";
	if(roll === 59)	return "1 **Belt of Fire Giant Strength**\n";
	if(roll === 60)	return "1 **Armor, +1 Breastplate**\n";
	if(roll === 61)	return "1 **Armor of Resistance (Breastplate)**\n";
	if(roll === 62)	return "1 **Candle of Invocation**\n";
	if(roll === 63)	return "1 **Armor, +2 Chain Mail**\n";
	if(roll === 64)	return "1 **Armor, +2 Chain Shirt**\n";
	if(roll === 65)	return "1 **Cloak of Arachnida**\n";
	if(roll === 66)	return "1 **Dancing Sword**\n";
	if(roll === 67)	return "1 **Demon Armor**\n";
	if(roll === 68)	return "1 **Dragon Scale Mail**\n";
	if(roll === 69)	return "1 **Dwarven Plate**\n";
	if(roll === 70)	return "1 **Dwarven Thrower**\n";
	if(roll === 71)	return "1 **Efreeti Bottle**\n";
	if(roll === 72)	return "1 **Figurine of Wondrous Power (Obsidian Steed)**\n";
	if(roll === 73)	return "1 **Frost Brand**\n";
	if(roll === 74)	return "1 **Helm of Brilliance**\n";
	if(roll === 75)	return "1 **Horn of Valhalla (Bronze)**\n";
	if(roll === 76)	return "1 **Instrument of the Bards (Anstruthharp)**\n";
	if(roll === 77)	return "1 **Ioun Stone (Absorption)**\n";
	if(roll === 78)	return "1 **Ioun Stone (Agility)**\n";
	if(roll === 79)	return "1 **Ioun Stone (Fortitude)**\n";
	if(roll === 80)	return "1 **Ioun Stone (Insight)**\n";
	if(roll === 81)	return "1 **Ioun Stone (Intellect)**\n";
	if(roll === 82)	return "1 **Ioun Stone (Leadership)**\n";
	if(roll === 83)	return "1 **Ioun Stone (Strength)**\n";
	if(roll === 84) return "1 **Armor, +2 Leather**\n";
	if(roll === 85)	return "1 **Manual of Bodily Health**\n";
	if(roll === 86)	return "1 **Manual of Gainful Exercise**\n";
	if(roll === 87)	return "1 **Manual of Golems**\n";
	if(roll === 88)	return "1 **Manual of Quickness of Action**\n";
	if(roll === 89)	return "1 **Mirror of Life Trapping**\n";
	if(roll === 90) return "1 **Nine Lives Stealer**\n";
	if(roll === 91)	return "1 **Oathbow**\n";
	if(roll === 92)	return "1 **Armor, +2 Scale Mail**\n";
	if(roll === 93)	return "1 **Spellguard Shield**\n";
	if(roll === 94)	return "1 **Armor, +1 Splint**\n";
	if(roll === 95)	return "1 **Armor of Resistance (Splint)**\n";
	if(roll === 96)	return "1 **Armor, +1 Studded Leather**\n";
	if(roll === 97)	return "1 **Armor of Resistance (Studded Leather)**\n";
	if(roll === 98) return "1 **Tome of Clear Thought**\n";
	if(roll === 99) return "1 **Tome of Leadership and Influence**\n";
	if(roll === 100) return "1 **Tome of Understanding**\n";
};
