module.exports = (roll) => {
	if(roll <= 15) return "+1 Weapon";
	if(roll <= 18) return "+1 Shield";
	if(roll <= 21) return "Sentinel Shield";
	if(roll <= 23) return "Amulet of Proof against Detection and Location";
	if(roll <= 25) return "Boots of Elvenkind";
	if(roll <= 27) return "Boots of Striding and Springing";
	if(roll <= 29) return "Bracer of Archery";
	if(roll <= 31) return "Brooch of Shielding";
	if(roll <= 33) return "Broom of Flying";
	if(roll <= 35) return "Cloak of Elvenkind";
	if(roll <= 37) return "Cloak of Protection";
	if(roll <= 39) return "Gauntlets of Ogre Power";
	if(roll <= 41) return "Hat of Disguise";
	if(roll <= 43) return "Javelin of Lightning";
	if(roll <= 45) return "Pearl of Power";
	if(roll <= 47) return "+1 Rod of the Pact Keeper";
	if(roll <= 49) return "Slippers of Spider Climbing";
	if(roll <= 51) return "Staff of the Adder";
	if(roll <= 53) return "Staff of the Python";
	if(roll <= 55) return "Sword of Vengence";
	if(roll <= 57) return "Trident of Fish Command";
	if(roll <= 59) return "Wand of Magic Missiles";
	if(roll <= 61) return "+1 Wand of the War Mage";
	if(roll <= 63) return "Wand of Web";
	if(roll <= 65) return "Weapon of Warning";
	if(roll === 66) return "Adamantine Armor (Chain Mail)";
	if(roll === 67) return "Adamantine Armor (Chain Shirt)";
	if(roll === 68) return "Adamantine Armor (Scale Mail)";
	if(roll === 69) return "Bag of Tricks (Gray)";
	if(roll === 70) return "Bag of Tricks (Rust)";
	if(roll === 71) return "Bag of Tricks (Tan)";
	if(roll === 72) return "Boots of the Winterlands";
	if(roll === 73) return "Circlet of Blasting";
	if(roll === 74) return "Deck of Illusions";
	if(roll === 75) return "Eversmoking Bottle";
	if(roll === 76) return "Eyes of Charming";
	if(roll === 77) return "Eyes of the Eagle";
	if(roll === 78) return "Figurine of Wondrous Power (Silver Raven)";
	if(roll === 79) return "Gem of Brightness";
	if(roll === 80) return "Gloves of Missile Snaring";
	if(roll === 81) return "Gloves of Swimming and Climbing";
	if(roll === 82) return "Gloves of Thievery";
	if(roll === 83) return "Headband of Intellect";
	if(roll === 84) return "Helm of Telepathy";
	if(roll === 85) return "Instrument of the Bards (Doss Lute)";
	if(roll === 86) return "Instrument of the Bards (Gochlucan Bandore)";
	if(roll === 87) return "Instrument of the Bards (Mac-Fuimidh Cittern)";
	if(roll === 88) return "Medallion of Thoughts";
	if(roll === 89) return "Necklace of Adaptation";
	if(roll === 90) return "Periapt of Wound Closure";
	if(roll === 91) return "Pipes of Haunting";
	if(roll === 92) return "Pipes of the Sewers";
	if(roll === 93) return "Ring of Jumping";
	if(roll === 94) return "Ring of Mind Shielding";
	if(roll === 95) return "Ring of Warmth";
	if(roll === 96) return "Ring of Water Walking";
	if(roll === 97) return "Quiver of Ehlonna";
	if(roll === 98) return "Stone of Good Luck";
	if(roll === 99) return "Wind Fan";
	if(roll === 100) return "Winged Boots";
};
