module.exports = () => {
	return [
		{ "roll": 15, "name": "**Potion of Greater Healing**", "link": "https://www.dndbeyond.com/magic-items/potion-of-healing" },
		{ "roll": 22, "name": "**Potion of Fire Breath**", "link": "https://aversten.obsidianportal.com/wiki_pages/potion-of-fire-breath" },
		{ "roll": 29, "name": "**Potion of Resistance**", "link": "https://www.dndbeyond.com/magic-items/potion-of-resistance" },
		{ "roll": 34, "name": "**+1 Ammunition**", "link": "https://www.dndbeyond.com/magic-items/ammunition-1" },
		{ "roll": 39, "name": "**Potion of Animal Friendship**", "link": "https://www.dndbeyond.com/magic-items/potion-of-animal-friendship" },
		{ "roll": 44, "name": "**Potion of Hill Giant Strength**", "link": "https://www.dndbeyond.com/magic-items/potion-of-giant-strength" },
		{ "roll": 49, "name": "**Potion of Growth**", "link": "https://www.dndbeyond.com/magic-items/potion-of-growth" },
		{ "roll": 54, "name": "**Potion of Water Breathing**", "link": "https://www.dndbeyond.com/magic-items/potion-of-water-breathing" },
		{ "roll": 59, "name": "**Spell Scroll (2nd level)**", "link": "https://www.dndbeyond.com/magic-items/spell-scroll" },
		{ "roll": 64, "name": "**Spell Scroll (3rd level)**", "link": "https://www.dndbeyond.com/magic-items/spell-scroll" },
		{ "roll": 67, "name": "**Bag of Holding**", "link": "https://www.dndbeyond.com/magic-items/bag-of-holding" },
		{ "roll": 70, "name": "**Keoghtom's Ointment**", "link": "https://aversten.obsidianportal.com/wiki_pages/keoghtoms-ointment" },
		{ "roll": 73, "name": "**Oil of Slipperiness**", "link": "https://www.dndbeyond.com/magic-items/oil-of-slipperiness" },
		{ "roll": 75, "name": "**Dust of Disappearance**", "link": "https://www.dndbeyond.com/magic-items/dust-of-disappearance" },
		{ "roll": 77, "name": "**Dust of Dryness**", "link": "https://www.dndbeyond.com/magic-items/dust-of-dryness" },
		{ "roll": 79, "name": "**Dust of Sneezing and Choking**", "link": "https://www.dndbeyond.com/magic-items/dust-of-sneezing-and-choking" },
		{ "roll": 81, "name": "**Elemental Gem**", "link": "https://www.dndbeyond.com/magic-items/elemental-gem" },
		{ "roll": 83, "name": "**Philter of Love**", "link": "https://www.dndbeyond.com/magic-items/philter-of-love" },
		{ "roll": 84, "name": "**Alchemy Jug**", "link": "https://aversten.obsidianportal.com/wiki_pages/alchemy-jug" },
		{ "roll": 85, "name": "**Cap of Water Breathing**", "link": "https://aversten.obsidianportal.com/wiki_pages/cap-of-water-breathing" },
		{ "roll": 86, "name": "**Cloak of the Manta Ray**", "link": "https://www.dndbeyond.com/magic-items/cloak-of-the-manta-ray" },
		{ "roll": 87, "name": "**Driftglobe**", "link": "https://aversten.obsidianportal.com/wikis/driftglobe" },
		{ "roll": 88, "name": "**Goggles of Night**", "link": "https://www.dndbeyond.com/magic-items/goggles-of-night" },
		{ "roll": 89, "name": "**Helm of Comprehending Languages**", "link": "https://www.dndbeyond.com/magic-items/helm-of-comprehending-languages" },
		{ "roll": 90, "name": "**Immovable Rod**", "link": "https://www.dndbeyond.com/magic-items/immovable-rod" },
		{ "roll": 91, "name": "**Lantern of Revealing**", "link": "https://www.dndbeyond.com/magic-items/lantern-of-revealing" },
		{ "roll": 92, "name": "**Mariner's Armor**", "link": "https://aversten.obsidianportal.com/wiki_pages/mariners-armor" },
		{ "roll": 93, "name": "**Mithral Armor**", "link": "https://www.dndbeyond.com/magic-items/mithral-armor" },
		{ "roll": 94, "name": "**Potion of Poison**", "link": "https://www.dndbeyond.com/magic-items/potion-of-poison" },
		{ "roll": 95, "name": "**Ring of Swimming**", "link": "https://www.dndbeyond.com/magic-items/ring-of-swimming" },
		{ "roll": 96, "name": "**Robe of Useful Items**", "link": "https://www.dndbeyond.com/magic-items/robe-of-useful-items" },
		{ "roll": 97, "name": "**Rope of Climbing**", "link": "https://www.dndbeyond.com/magic-items/rope-of-climbing" },
		{ "roll": 98, "name": "**Saddle of the Cavalier**", "link": "https://aversten.obsidianportal.com/wikis/saddle-of-the-cavalier" },
		{ "roll": 99, "name": "**Wand of Magic Detection**", "link": "https://www.dndbeyond.com/magic-items/wand-of-magic-detection" },
		{ "roll": 100, "name": "**Wand of Secrets**", "link": "https://www.dndbeyond.com/magic-items/wand-of-secrets" },
	];
};
