module.exports = (roll) => {
	if(roll <= 11) return { name:"**+2 Weapon**", link:"https://www.dndbeyond.com/magic-items/weapon-2" };
	if(roll <= 14){
		const figurine = d8();
		if(figurine === 1) return { name:"**Figurine of Wondrous Power (Bronze Griffon)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-bronze-griffon" };
		if(figurine === 2) return { name:"**Figurine of Wondrous Power (Ebony Fly)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-ebony-fly" };
		if(figurine === 3) return { name:"**Figurine of Wondrous Power (Golden Lions)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-golden-lions" };
		if(figurine === 4) return { name:"**Figurine of Wondrous Power (Ivory Goats)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-ivory-goats" };
		if(figurine === 5) return { name:"**Figurine of Wondrous Power (Marble Elephant)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-marble-elephant" };
		if(figurine <= 7) return { name:"**Figurine of Wondrous Power (Onyx Dog)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-onyx-dog" };
		if(figurine === 8) return { name:"**Figurine of Wondrous Power (Serpentine Owl)**", link:"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-serpentine-owl" };
	}
	if(roll === 15)	return { name:"**Adamantine Armor (Breastplate)**", link:"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(roll === 16)	return { name:"**Adamantine Armor (Splint)**", link:"https://www.dndbeyond.com/magic-items/adamantine-armor" };
	if(roll === 17)	return { name:"**Amulet of Health**", link:"https://www.dndbeyond.com/magic-items/amulet-of-health" };
	if(roll === 18)	return { name:"**Armor of Vulnerability**", link:"https://www.dndbeyond.com/magic-items/armor-of-vulnerability" };
	if(roll === 19)	return { name:"**Arrow Catching Shield**", link:"https://www.dndbeyond.com/magic-items/arrow-catching-shield" };
	if(roll === 20)	return { name:"**Belt of Dwarvenkind**", link:"https://www.dndbeyond.com/magic-items/belt-of-dwarvenkind" };
	if(roll === 21)	return { name:"**Belt of Hill Giant Strength**", link:"https://www.dndbeyond.com/magic-items/belt-of-hill-giant-strength" };
	if(roll === 22)	return { name:"**Berserker Axe**", link:"https://www.dndbeyond.com/magic-items/berserker-axe" };
	if(roll === 23)	return { name:"**Boots of Levitation**", link:"https://www.dndbeyond.com/magic-items/boots-of-levitation" };
	if(roll === 24)	return { name:"**Boots of Speed**", link:"https://www.dndbeyond.com/magic-items/boots-of-speed" };
	if(roll === 25)	return { name:"**Bowl of Commanding Water Elementals**", link:"https://www.dndbeyond.com/magic-items/bowl-of-commanding-water-elementals" };
	if(roll === 26)	return { name:"**Bracers of Defense**", link:"https://www.dndbeyond.com/magic-items/bracers-of-defense" };
	if(roll === 27)	return { name:"**Brazier of Commanding Fire Elementals**", link:"https://www.dndbeyond.com/magic-items/brazier-of-commanding-fire-elementals" };
	if(roll === 28)	return { name:"**Cape of the Mountebank**", link:"https://www.dndbeyond.com/magic-items/cape-of-the-mountebank" };
	if(roll === 29)	return { name:"**Censer of Controlling Air Elementals**", link:"https://www.dndbeyond.com/magic-items/censer-of-controlling-air-elementals" };
	if(roll === 30)	return { name:"**Armor, +1 Chain Mail**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 31)	return { name:"**Armor of Resistance (Chain Mail)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 32)	return { name:"**Armor of Resistance (Chain Shirt)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 33)	return { name:"**Armor, +1 Chain Shirt**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 34)	return { name:"**Cloak of Displacement**", link:"https://www.dndbeyond.com/magic-items/cloak-of-displacement" };
	if(roll === 35)	return { name:"**Cloak of the Bat**", link:"https://www.dndbeyond.com/magic-items/cloak-of-the-bat" };
	if(roll === 36)	return { name:"**Cube of Force**", link:"https://www.dndbeyond.com/magic-items/cube-of-force" };
	if(roll === 37)	return { name:"**Daern's Instant Fortress**", link:"https://aversten.obsidianportal.com/wiki_pages/daerns-instant-fortress" };
	if(roll === 38)	return { name:"**Dagger of Venom**", link:"https://www.dndbeyond.com/magic-items/dagger-of-venom" };
	if(roll === 39)	return { name:"**Dimensional Shackles**", link:"https://www.dndbeyond.com/magic-items/dimensional-shackles" };
	if(roll === 40)	return { name:"**Dragon Slayer**", link:"https://www.dndbeyond.com/magic-items/dragon-slayer" };
	if(roll === 41)	return { name:"**Elven Chain**", link:"https://www.dndbeyond.com/magic-items/elven-chain" };
	if(roll === 42)	return { name:"**Flame Tongue**", link:"https://www.dndbeyond.com/magic-items/flame-tongue" };
	if(roll === 43)	return { name:"**Gem of Seeing**", link:"https://www.dndbeyond.com/magic-items/gem-of-seeing" };
	if(roll === 44)	return { name:"**Giant Slayer**", link:"https://www.dndbeyond.com/magic-items/giant-slayer" };
	if(roll === 45)	return { name:"**Glamoured Studded Leather**", link:"https://www.dndbeyond.com/magic-items/glamoured-studded-leather" };
	if(roll === 46)	return { name:"**Helm of Teleportation**", link:"https://www.dndbeyond.com/magic-items/helm-of-teleportation" };
	if(roll === 47)	return { name:"**Horn of Blasting**", link:"https://www.dndbeyond.com/magic-items/horn-of-blasting" };
	if(roll === 48)	return { name:"**Horn of Valhalla (Silver or Brass)**", link:"https://www.dndbeyond.com/magic-items/horn-of-valhalla" };
	if(roll === 49)	return { name:"**Instrument of the Bards (Canaith Mandolin)**", link:"https://aversten.obsidianportal.com/wiki_pages/instrument-of-the-bards" };
	if(roll === 50)	return { name:"**Instrument of the Bards (Cii Lyre)**", link:"https://aversten.obsidianportal.com/wiki_pages/instrument-of-the-bards" };
	if(roll === 51)	return { name:"**Ioun Stone (Awareness)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-awareness" };
	if(roll === 52)	return { name:"**Ioun Stone (Protection)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-protection" };
	if(roll === 53)	return { name:"**Ioun Stone (Reserve)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-reserve" };
	if(roll === 54)	return { name:"**Ioun Stone (Sustenance)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-sustenance" };
	if(roll === 55)	return { name:"**Iron Bands of Bilarro**", link:"https://aversten.obsidianportal.com/wikis/iron-bands-of-bilarro" };
	if(roll === 56)	return { name:"**Armor, +1 Leather**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 57)	return { name:"**Armor of Resistance (Leather)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 58)	return { name:"**Mace of Disruption**", link:"https://www.dndbeyond.com/magic-items/mace-of-disruption" };
	if(roll === 59)	return { name:"**Mace of Smiting**", link:"https://www.dndbeyond.com/magic-items/mace-of-smiting" };
	if(roll === 60)	return { name:"**Mace of Terror**", link:"https://www.dndbeyond.com/magic-items/mace-of-terror" };
	if(roll === 61)	return { name:"**Mantle of Spell Resistance**", link:"https://www.dndbeyond.com/magic-items/mantle-of-spell-resistance" };
	if(roll === 62)	return { name:"**Necklace of Prayer Beads**", link:"https://www.dndbeyond.com/magic-items/necklace-of-prayer-beads" };
	if(roll === 63)	return { name:"**Periapt of Proof against Poison**", link:"https://www.dndbeyond.com/magic-items/periapt-of-proof-against-poison" };
	if(roll === 64)	return { name:"**Ring of Animal Influence**", link:"https://www.dndbeyond.com/magic-items/ring-of-animal-influence" };
	if(roll === 65)	return { name:"**Ring of Evasion**", link:"https://www.dndbeyond.com/magic-items/ring-of-evasion" };
	if(roll === 66)	return { name:"**Ring of Feather Falling**", link:"https://www.dndbeyond.com/magic-items/ring-of-feather-falling" };
	if(roll === 67)	return { name:"**Ring of Free Action**", link:"https://www.dndbeyond.com/magic-items/ring-of-free-action" };
	if(roll === 68)	return { name:"**Ring of Protection**", link:"https://www.dndbeyond.com/magic-items/ring-of-protection" };
	if(roll === 69)	return { name:"**Ring of Resistance**", link:"https://www.dndbeyond.com/magic-items/ring-of-resistance" };
	if(roll === 70)	return { name:"**Ring of Spell Storing**", link:"https://www.dndbeyond.com/magic-items/ring-of-spell-storing" };
	if(roll === 71)	return { name:"**Ring of the Ram**", link:"https://www.dndbeyond.com/magic-items/ring-of-the-ram" };
	if(roll === 72)	return { name:"**Ring of X-Ray Vision**", link:"https://www.dndbeyond.com/magic-items/ring-of-x-ray-vision" };
	if(roll === 73)	return { name:"**Robe of Eyes**", link:"https://www.dndbeyond.com/magic-items/robe-of-eyes" };
	if(roll === 74)	return { name:"**Rod of Rulership**", link:"https://www.dndbeyond.com/magic-items/rod-of-rulership" };
	if(roll === 75)	return { name:"**+2 Rod of the Pact Keeper**", link:"https://aversten.obsidianportal.com/search?utf8=%E2%9C%93&q=Rod+of+the+Pact+Keeper" };
	if(roll === 76)	return { name:"**Rope of Entanglement**", link:"https://www.dndbeyond.com/magic-items/rope-of-entanglement" };
	if(roll === 77)	return { name:"**Armor, +1 Scale Mail**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll === 78)	return { name:"**Armor of Resistance (Scale Mail)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 79)	return { name:"**+2 Shield**", link:"https://www.dndbeyond.com/magic-items/shield-2" };
	if(roll === 80)	return { name:"**Shield of Missile Attraction**", link:"https://www.dndbeyond.com/magic-items/shield-of-missile-attraction" };
	if(roll === 81)	return { name:"**Staff of Charming**", link:"https://www.dndbeyond.com/magic-items/staff-of-charming" };
	if(roll === 82)	return { name:"**Staff of Healing**", link:"https://www.dndbeyond.com/magic-items/staff-of-healing" };
	if(roll === 83)	return { name:"**Staff of Swarming Insects**", link:"https://www.dndbeyond.com/magic-items/staff-of-swarming-insects" };
	if(roll === 84) return { name:"**Staff of the Woodlands**", link:"https://www.dndbeyond.com/magic-items/staff-of-the-woodlands" };
	if(roll === 85)	return { name:"**Staff of Withering**", link:"https://www.dndbeyond.com/magic-items/staff-of-withering" };
	if(roll === 86)	return { name:"**Stone of Controlling Earth Elementals**", link:"https://www.dndbeyond.com/magic-items/stone-of-controlling-earth-elementals" };
	if(roll === 87)	return { name:"**Sun Blade**", link:"https://www.dndbeyond.com/magic-items/sun-blade" };
	if(roll === 88)	return { name:"**Sword of Life Stealing**", link:"https://www.dndbeyond.com/magic-items/sword-of-life-stealing" };
	if(roll === 89)	return { name:"**Sword of Wounding**", link:"https://www.dndbeyond.com/magic-items/sword-of-wounding" };
	if(roll === 90) return { name:"**Tentacle Rod**", link:"https://aversten.obsidianportal.com/wikis/tentacle-rod" };
	if(roll === 91)	return { name:"**Vicious Weapon**", link:"https://www.dndbeyond.com/magic-items/vicious-weapon" };
	if(roll === 92)	return { name:"**Wand of Binding**", link:"https://www.dndbeyond.com/magic-items/wand-of-binding" };
	if(roll === 93)	return { name:"**Wand of Enemy Detection**", link:"https://www.dndbeyond.com/magic-items/wand-of-enemy-detection" };
	if(roll === 94)	return { name:"**Wand of Fear**", link:"https://www.dndbeyond.com/magic-items/wand-of-fear" };
	if(roll === 95)	return { name:"**Wand of Fireballs**", link:"https://www.dndbeyond.com/magic-items/wand-of-fireballs" };
	if(roll === 96)	return { name:"**Wand of Lightning Bolts**", link:"https://www.dndbeyond.com/magic-items/wand-of-lightning-bolts" };
	if(roll === 97)	return { name:"**Wand of Paralysis**", link:"https://www.dndbeyond.com/magic-items/wand-of-paralysis" };
	if(roll === 98) return { name:"**+2 Wand of the War Mage**", link:"https://www.dndbeyond.com/magic-items/wand-of-the-war-mage" };
	if(roll === 99) return { name:"**Wand of Wonder**", link:"https://www.dndbeyond.com/magic-items/wand-of-wonder" };
	if(roll === 100) return { name:"**Wings of Flying**", link:"https://www.dndbeyond.com/magic-items/wings-of-flying" };
};
