module.exports = (roll) => {
	if(roll <= 5) return "1 **Defender**\n";
	if(roll <= 10) return "1 **Hammer of Thunderbolts**\n";
	if(roll <= 20) return "1 **Sword of Answering**\n";
	if(roll <= 23) return "1 **Holy Avenger**\n";
	if(roll <= 26) return "1 **Ring of Djinni Summoning**\n";
	if(roll <= 29) return "1 **Ring of Invisibility**\n";
	if(roll <= 32) return "1 **Ring of Spell Turning**\n";
	if(roll <= 38) return "1 **Rod of Lordly Might**\n";
	if(roll <= 41) return "1 **Vorpal Sword**\n";
	if(roll <= 43) return "1 **Belt of Cloud Giant Strength**\n";
	if(roll <= 45) return "1 **Armor, +2 Breastplate**\n";
	if(roll <= 47) return "1 **Armor, +3 Chain Mail**\n";
	if(roll <= 49) return "1 **Armor, +3 Chain Shirt**\n";
	if(roll <= 51) return "1 **Cloak of Invisibility**\n";
	if(roll <= 53) return "1 **Crystal Ball (Legendary Version)**\n";
	if(roll <= 55) return "1 **Armor, +1 Half Plate**\n";
	if(roll <= 57) return "1 **Iron Flask**\n";
	if(roll <= 59) return "1 **Armor, +3 Leather**\n";
	if(roll <= 61) return "1 **Armor, +1 Plate**\n";
	if(roll <= 63) return "1 **Robe of the Archmagi**\n";
	if(roll <= 65) return "1 **Rod of Resurrection**\n";
	if(roll <= 67) return "1 **Armor, +1 Scale Mail**\n";
	if(roll <= 69)	return "1 **Scarab of Protection**\n";
	if(roll <= 71)	return "1 **Armor, +2 Splint**\n";
	if(roll <= 73)	return "1 **Armor, +2 Studded Leather**\n";
	if(roll <= 75)	return "1 **Well of Many Worlds**\n";
	if(roll === 76){
		const armor = d12();
		if(armor <= 2) return "1 **Armor, +2 Half Plate**\n";
		if(armor <= 4) return "1 **Armor, +2 Plate**\n";
		if(armor <= 6) return "1 **Armor, +3 Studded Leather**\n";
		if(armor <= 8) return "1 **Armor, +3 Breastplate**\n";
		if(armor <= 10) return "1 **Armor, +3 Splint**\n";
		if(armor === 11) return "1 **Armor, +3 Half Plate**\n";
		if(armor === 12) return "1 **Armor, +3 Plate**\n";
	}
	if(roll === 77)	return "1 **Apparatus of Kwalish**\n";
	if(roll === 78)	return "1 **Armor of Invulnerability**\n";
	if(roll === 79)	return "1 ***Belt of Storm Giant Strength*\n";
	if(roll === 80)	return "1 **Cubic Gate**\n";
	if(roll === 81)	return "1 **Deck of Many Things**\n";
	if(roll === 82)	return "1 **Efreeti Chain**\n";
	if(roll === 83)	return "1 **Armor of Resistance (Half Plate)**\n";
	if(roll === 84) return "1 **Horn of Valhalla (Iron)**\n";
	if(roll === 85)	return "1 **Instrument of the Bards (Ollamh Harp)**\n";
	if(roll === 86)	return "1 **Ioun Stone (Greater Absorption)**\n";
	if(roll === 87)	return "1 **Ioun Stone (Mastery)**\n";
	if(roll === 88)	return "1 **Ioun Stone (Regneration)**\n";
	if(roll === 89) return "1 **Plate Armor of Etherealness**\n";
	if(roll === 90)	return "1 **Plate Armor of Resistance**\n";
	if(roll === 91) return "1 **Ring of Air Elemental Command**\n";
	if(roll === 92)	return "1 **Ring of Earth Elemental Command**\n";
	if(roll === 94)	return "1 **Ring of Fire Elemental Command**\n";
	if(roll === 94)	return "1 **Ring of Three Wishes**\n";
	if(roll === 95)	return "1 **Ring of Water Elemental Command**\n";
	if(roll === 96)	return "1 **Sphere of Annihilation**\n";
	if(roll === 97)	return "1 **Talisman of Pure Good**\n";
	if(roll === 98)	return "1 **Talisman of the Sphere**\n";
	if(roll === 99) return "1 **Talisman of Ultimate Evil**\n";
	if(roll === 100) return "1 **Tome of the stilled Tongue**\n";
};
