module.exports = (roll) => {
	if(roll <= 5) return { name:"**Defender**", link:"https://www.dndbeyond.com/magic-items/defender" };
	if(roll <= 10) return { name:"**Hammer of Thunderbolts**", link:"https://www.dndbeyond.com/magic-items/hammer-of-thunderbolts" };
	if(roll <= 20) return { name:"**Sword of Answering**", link:"https://aversten.obsidianportal.com/wiki_pages/sword-of-answering" };
	if(roll <= 23) return { name:"**Holy Avenger**", link:"https://www.dndbeyond.com/magic-items/holy-avenger" };
	if(roll <= 26) return { name:"**Ring of Djinni Summoning**", link:"https://www.dndbeyond.com/magic-items/ring-of-djinni-summoning" };
	if(roll <= 29) return { name:"**Ring of Invisibility**", link:"https://www.dndbeyond.com/magic-items/ring-of-invisibility" };
	if(roll <= 32) return { name:"**Ring of Spell Turning**", link:"https://www.dndbeyond.com/magic-items/ring-of-spell-turning" };
	if(roll <= 38) return { name:"**Rod of Lordly Might**", link:"https://www.dndbeyond.com/magic-items/rod-of-lordly-might" };
	if(roll <= 41) return { name:"**Vorpal Sword**", link:"https://www.dndbeyond.com/magic-items/vorpal-sword" };
	if(roll <= 43) return { name:"**Belt of Cloud Giant Strength**", link:"https://www.dndbeyond.com/magic-items/belt-of-cloud-giant-strength" };
	if(roll <= 45) return { name:"**Armor, +2 Breastplate**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll <= 47) return { name:"**Armor, +3 Chain Mail**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
	if(roll <= 49) return { name:"**Armor, +3 Chain Shirt**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
	if(roll <= 51) return { name:"**Cloak of Invisibility**", link:"https://aversten.obsidianportal.com/wiki_pages/cloak-of-invisibility" };
	if(roll <= 53) return { name:"**Crystal Ball (Legendary Version)**", link:"https://www.dndbeyond.com/magic-items/crystal-ball" };
	if(roll <= 55) return { name:"**Armor, +1 Half Plate**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll <= 57) return { name:"**Iron Flask**", link:"https://www.dndbeyond.com/magic-items/iron-flask" };
	if(roll <= 59) return { name:"**Armor, +3 Leather**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
	if(roll <= 61) return { name:"**Armor, +1 Plate**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll <= 63) return { name:"**Robe of the Archmagi**", link:"https://www.dndbeyond.com/magic-items/robe-of-the-archmagi" };
	if(roll <= 65) return { name:"**Rod of Resurrection**", link:"https://aversten.obsidianportal.com/wiki_pages/rod-of-resurrection" };
	if(roll <= 67) return { name:"**Armor, +1 Scale Mail**", link:"https://www.dndbeyond.com/magic-items/armor-1" };
	if(roll <= 69)	return { name:"**Scarab of Protection**", link:"https://www.dndbeyond.com/magic-items/scarab-of-protection" };
	if(roll <= 71)	return { name:"**Armor, +2 Splint**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll <= 73)	return { name:"**Armor, +2 Studded Leather**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
	if(roll <= 75)	return { name:"**Well of Many Worlds**", link:"https://www.dndbeyond.com/magic-items/well-of-many-worlds" };
	if(roll === 76){
		const armor = d12();
		if(armor <= 2) return { name:"**Armor, +2 Half Plate**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
		if(armor <= 4) return { name:"**Armor, +2 Plate**", link:"https://www.dndbeyond.com/magic-items/armor-2" };
		if(armor <= 6) return { name:"**Armor, +3 Studded Leather**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
		if(armor <= 8) return { name:"**Armor, +3 Breastplate**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
		if(armor <= 10) return { name:"**Armor, +3 Splint**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
		if(armor === 11) return { name:"**Armor, +3 Half Plate**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
		if(armor === 12) return { name:"**Armor, +3 Plate**", link:"https://www.dndbeyond.com/magic-items/armor-3" };
	}
	if(roll === 77)	return { name:"**Apparatus of Kwalish**", link:"https://aversten.obsidianportal.com/wiki_pages/apparatus-of-kwalish" };
	if(roll === 78)	return { name:"**Armor of Invulnerability**", link:"https://www.dndbeyond.com/magic-items/armor-of-invulnerability" };
	if(roll === 79)	return { name:"**Belt of Storm Giant Strength*", link:"https://www.dndbeyond.com/magic-items/belt-of-storm-giant-strength" };
	if(roll === 80)	return { name:"**Cubic Gate**", link:"https://www.dndbeyond.com/magic-items/cubic-gate" };
	if(roll === 81)	return { name:"**Deck of Many Things**", link:"https://www.dndbeyond.com/magic-items/deck-of-many-things" };
	if(roll === 82)	return { name:"**Efretti Chain**", link:"https://aversten.obsidianportal.com/wiki_pages/efretti-chain" };
	if(roll === 83)	return { name:"**Armor of Resistance (Half Plate)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 84) return { name:"**Horn of Valhalla (Iron)**", link:"https://www.dndbeyond.com/magic-items/horn-of-valhalla-iron" };
	if(roll === 85)	return { name:"**Instrument of the Bards (Ollamh Harp)**", link:"https://aversten.obsidianportal.com/wiki_pages/instrument-of-the-bards" };
	if(roll === 86)	return { name:"**Ioun Stone (Greater Absorption)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-greater-absorption" };
	if(roll === 87)	return { name:"**Ioun Stone (Mastery)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-mastery" };
	if(roll === 88)	return { name:"**Ioun Stone (Regneration)**", link:"https://www.dndbeyond.com/magic-items/ioun-stone-of-regeneration" };
	if(roll === 89) return { name:"**Plate Armor of Etherealness**", link:"https://www.dndbeyond.com/magic-items/plate-armor-of-etherealness" };
	if(roll === 90)	return { name:"**Armor of Resistance (Plate)**", link:"https://www.dndbeyond.com/magic-items/armor-of-resistance" };
	if(roll === 91) return { name:"**Ring of Air Elemental Command**", link:"https://www.dndbeyond.com/magic-items/ring-of-air-elemental-command" };
	if(roll === 92)	return { name:"**Ring of Earth Elemental Command**", link:"https://www.dndbeyond.com/magic-items/ring-of-earth-elemental-command" };
	if(roll === 94)	return { name:"**Ring of Fire Elemental Command**", link:"https://www.dndbeyond.com/magic-items/ring-of-fire-elemental-command" };
	if(roll === 94)	return { name:"**Ring of Three Wishes**", link:"https://www.dndbeyond.com/magic-items/ring-of-three-wishes" };
	if(roll === 95)	return { name:"**Ring of Water Elemental Command**", link:"https://www.dndbeyond.com/magic-items/ring-of-water-elemental-command" };
	if(roll === 96)	return { name:"**Sphere of Annihilation**", link:"https://www.dndbeyond.com/magic-items/sphere-of-annihilation" };
	if(roll === 97)	return { name:"**Talisman of Pure Good**", link:"https://www.dndbeyond.com/magic-items/talisman-of-pure-good" };
	if(roll === 98)	return { name:"**Talisman of the Sphere**", link:"https://www.dndbeyond.com/magic-items/talisman-of-the-sphere" };
	if(roll === 99) return { name:"**Talisman of Ultimate Evil**", link:"https://www.dndbeyond.com/magic-items/talisman-of-ultimate-evil" };
	if(roll === 100) return { name:"**Tome of the Stilled Tongue**", link:"https://aversten.obsidianportal.com/wiki_pages/tome-of-the-stilled-tongue" };
};
