module.exports = () => {
	return [
		{ "roll": 10, "name": "**+3 Weapon**", "link":"https://www.dndbeyond.com/magic-items/weapon-3" },
		{ "roll": 12, "name": "**Amulet of the Planes**", "link":"https://www.dndbeyond.com/magic-items/amulet-of-the-planes" },
		{ "roll": 14, "name": "**Carpet of Flying**", "link":"https://www.dndbeyond.com/magic-items/carpet-of-flying" },
		{ "roll": 16, "name": "**Crystal Ball (Very Rare Version)**", "link":"https://www.dndbeyond.com/magic-items/crystal-ball" },
		{ "roll": 18, "name": "**Ring of Regeneration**", "link":"https://www.dndbeyond.com/magic-items/ring-of-regeneration" },
		{ "roll": 20, "name": "**Ring of Shooting Stars**", "link":"https://www.dndbeyond.com/magic-items/ring-of-shooting-stars" },
		{ "roll": 22, "name": "**Ring Telekinesis**", "link":"https://www.dndbeyond.com/magic-items/ring-of-telekinesis" },
		{ "roll": 24, "name": "**Robe of Scintillating Colors**", "link":"https://www.dndbeyond.com/magic-items/robe-of-scintillating-colors" },
		{ "roll": 26, "name": "**Robe of Stars**", "link":"https://www.dndbeyond.com/magic-items/robe-of-stars" },
		{ "roll": 28, "name": "**Rod of Absorption**", "link":"https://www.dndbeyond.com/magic-items/rod-of-absorption" },
		{ "roll": 30, "name": "**Rod of Alertness**", "link":"https://www.dndbeyond.com/magic-items/rod-of-alertness" },
		{ "roll": 32, "name": "**Rod of Security**", "link":"https://www.dndbeyond.com/magic-items/rod-of-security" },
		{ "roll": 34, "name": "**+3 Rod of the Pact Keeper**", "link":"https://aversten.obsidianportal.com/wiki_pages/rod-of-the-pact-keeper" },
		{ "roll": 36, "name": "**Scimitar of Speed**", "link":"https://www.dndbeyond.com/magic-items/scimitar-of-speed" },
		{ "roll": 38, "name": "**+3 Shield**", "link":"https://www.dndbeyond.com/magic-items/shield-3" },
		{ "roll": 40, "name": "**Staff of Fire**", "link":"https://www.dndbeyond.com/magic-items/staff-of-fire" },
		{ "roll": 42, "name": "**Staff of Frost**", "link":"https://www.dndbeyond.com/magic-items/staff-of-frost" },
		{ "roll": 44, "name": "**Staff of Power**", "link":"https://www.dndbeyond.com/magic-items/staff-of-power" },
		{ "roll": 46, "name": "**Staff of Striking**", "link":"https://www.dndbeyond.com/magic-items/staff-of-striking" },
		{ "roll": 48, "name": "**Staff of Thunder and Lightning**", "link":"https://www.dndbeyond.com/magic-items/staff-of-thunder-and-lightning" },
		{ "roll": 52, "name": "**Sword of Sharpness**", "link":"https://www.dndbeyond.com/magic-items/sword-of-sharpness" },
		{ "roll": 54, "name": "**Wand of Polymorph**", "link":"https://www.dndbeyond.com/magic-items/wand-of-polymorph" },
		{ "roll": 55, "name": "**+3 Wand of the War Mage**", "link":"https://www.dndbeyond.com/magic-items/wand-of-the-war-mage" },
		{ "roll": 56, "name": "**Adamantine Armor (Half Plate)**", "link":"https://www.dndbeyond.com/magic-items/adamantine-armor" },
		{ "roll": 57, "name": "**Adamantine Armor (Plate)**", "link":"https://www.dndbeyond.com/magic-items/adamantine-armor" },
		{ "roll": 58, "name": "**Animated Shield**", "link":"https://www.dndbeyond.com/magic-items/animated-shield" },
		{ "roll": 59, "name": "**Belt of Fire Giant Strength**", "link":"https://www.dndbeyond.com/magic-items/belt-of-fire-giant-strength" },
		{ "roll": 60, "name": "**Armor, +1 Breastplate**", "link":"https://www.dndbeyond.com/magic-items/armor-1" },
		{ "roll": 61, "name": "**Armor of Resistance (Breastplate)**", "link":"https://www.dndbeyond.com/magic-items/armor-of-resistance" },
		{ "roll": 62, "name": "**Candle of Invocation**", "link":"https://www.dndbeyond.com/magic-items/candle-of-invocation" },
		{ "roll": 63, "name": "**Armor, +2 Chain Mail**", "link":"https://www.dndbeyond.com/magic-items/armor-2" },
		{ "roll": 64, "name": "**Armor, +2 Chain Shirt**", "link":"https://www.dndbeyond.com/magic-items/armor-2" },
		{ "roll": 65, "name": "**Cloak of Arachnida**", "link":"https://www.dndbeyond.com/magic-items/cloak-of-arachnida" },
		{ "roll": 66, "name": "**Dancing Sword**", "link":"https://www.dndbeyond.com/magic-items/dancing-sword" },
		{ "roll": 67, "name": "**Demon Armor**", "link":"https://www.dndbeyond.com/magic-items/demon-armor" },
		{ "roll": 68, "name": "**Dragon Scale Mail**", "link":"https://www.dndbeyond.com/magic-items/dragon-scale-mail" },
		{ "roll": 69, "name": "**Dwarven Plate**", "link":"https://www.dndbeyond.com/magic-items/dwarven-plate" },
		{ "roll": 70, "name": "**Dwarven Thrower**", "link":"https://www.dndbeyond.com/magic-items/dwarven-thrower" },
		{ "roll": 71, "name": "**Efreeti Bottle**", "link":"https://www.dndbeyond.com/magic-items/efreeti-bottle" },
		{ "roll": 72, "name": "**Figurine of Wondrous Power (Obsidian Steed)**", "link":"https://www.dndbeyond.com/magic-items/figurine-of-wondrous-power-obsidian-steed" },
		{ "roll": 73, "name": "**Frost Brand**", "link":"https://www.dndbeyond.com/magic-items/frost-brand" },
		{ "roll": 74, "name": "**Helm of Brilliance**", "link":"https://www.dndbeyond.com/magic-items/helm-of-brilliance" },
		{ "roll": 75, "name": "**Horn of Valhalla (Bronze)**", "link":"https://www.dndbeyond.com/magic-items/horn-of-valhalla-bronze" },
		{ "roll": 76, "name": "**Instrument of the Bards (Anstruth Harp)**", "link":"https://aversten.obsidianportal.com/wiki_pages/instrument-of-the-bards" },
		{ "roll": 77, "name": "**Ioun Stone (Absorption)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-absorption" },
		{ "roll": 78, "name": "**Ioun Stone (Agility)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-agility" },
		{ "roll": 79, "name": "**Ioun Stone (Fortitude)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-fortitude" },
		{ "roll": 80, "name": "**Ioun Stone (Insight)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-insight" },
		{ "roll": 81, "name": "**Ioun Stone (Intellect)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-intellect" },
		{ "roll": 82, "name": "**Ioun Stone (Leadership)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-leadership" },
		{ "roll": 83, "name": "**Ioun Stone (Strength)**", "link":"https://www.dndbeyond.com/magic-items/ioun-stone-of-strength" },
		{ "roll": 84, "name": "**Armor, +2 Leather**", "link":"https://www.dndbeyond.com/magic-items/armor-2" },
		{ "roll": 85, "name": "**Manual of Bodily Health**", "link":"https://www.dndbeyond.com/magic-items/manual-of-bodily-health" },
		{ "roll": 86, "name": "**Manual of Gainful Exercise**", "link":"https://www.dndbeyond.com/magic-items/manual-of-gainful-exercise" },
		{ "roll": 87, "name": "**Manual of Golems**", "link":"https://www.dndbeyond.com/magic-items/manual-of-golems" },
		{ "roll": 88, "name": "**Manual of Quickness of Action**", "link":"https://www.dndbeyond.com/magic-items/manual-of-quickness-of-action" },
		{ "roll": 89, "name": "**Mirror of Life Trapping**", "link":"https://www.dndbeyond.com/magic-items/mirror-of-life-trapping" },
		{ "roll": 90, "name": "**Nine Lives Stealer**", "link":"https://www.dndbeyond.com/magic-items/nine-lives-stealer" },
		{ "roll": 91, "name": "**Oathbow**", "link":"https://www.dndbeyond.com/magic-items/oathbow" },
		{ "roll": 92, "name": "**Armor, +2 Scale Mail**", "link":"https://www.dndbeyond.com/magic-items/armor-2" },
		{ "roll": 93, "name": "**Spellguard Shield**", "link":"https://www.dndbeyond.com/magic-items/spellguard-shield" },
		{ "roll": 94, "name": "**Armor, +1 Splint**", "link":"https://www.dndbeyond.com/magic-items/armor-1" },
		{ "roll": 95, "name": "**Armor of Resistance (Splint)**", "link":"https://www.dndbeyond.com/magic-items/armor-of-resistance" },
		{ "roll": 96, "name": "**Armor, +1 Studded Leather**", "link":"https://www.dndbeyond.com/magic-items/armor-1" },
		{ "roll": 97, "name": "**Armor of Resistance (Studded Leather)**", "link":"https://www.dndbeyond.com/magic-items/armor-of-resistance" },
		{ "roll": 98, "name": "**Tome of Clear Thought**", "link":"https://www.dndbeyond.com/magic-items/tome-of-clear-thought" },
		{ "roll": 99, "name": "**Tome of Leadership and Influence**", "link":"https://www.dndbeyond.com/magic-items/tome-of-leadership-and-influence" },
		{ "roll": 100, "name": "**Tome of Understanding**", "link":"https://www.dndbeyond.com/magic-items/tome-of-understanding" },
	];
};
