module.exports = (roll) => {
	if(roll <= 11){
		return "+2 Weapon";
	}
	if(roll <= 14){
		const figurine = d8();
		if(figurine === 1) return "Figurine of Wondrous Power (Bronze Griffon)";
		if(figurine === 2) return "Figurine of Wondrous Power (Ebony Fly)";
		if(figurine === 3) return "Figurine of Wondrous Power (Golden Lions)";
		if(figurine === 4) return "Figurine of Wondrous Power (Ivory Goats)";
		if(figurine === 5) return "Figurine of Wondrous Power (Marble Elephant)";
		if(figurine <= 7) return "Figurine of Wondrous Power (Onyx Dog)";
		if(figurine === 8) return "Figurine of Wondrous Power (Serpentine Owl)";
	}
	if(roll === 15)	return "Adamantine Armor (Breastplate)";
	if(roll === 16)	return "Adamantine Armor (Splint)";
	if(roll === 17)	return "Amulet of Health";
	if(roll === 18)	return "Armor of Vulnerability";
	if(roll === 19)	return "Arrow Catching Shield";
	if(roll === 20)	return "Belt of Dwarvenkind";
	if(roll === 21)	return "Belt of Hill Giant Strength";
	if(roll === 22)	return "Beserker Axe";
	if(roll === 23)	return "Boots of Levitation";
	if(roll === 24)	return "Boots of Speed";
	if(roll === 25)	return "Bowl of Commanding Fire Elementals";
	if(roll === 26)	return "Bracers of Defence";
	if(roll === 27)	return "Brazier of Commanding Fire Elementals";
	if(roll === 28)	return "Cape of the Mountebank";
	if(roll === 29)	return "Censer of Controlling Air Elementals";
	if(roll === 30)	return "Armor, +1 Chain Mail";
	if(roll === 31)	return "Armor of Resistance (Chain Mail)";
	if(roll === 32)	return "Armor of Resistance (Chain Shirt)";
	if(roll === 33)	return "Armor, +1 Chain Shirt";
	if(roll === 34)	return "Cloak of Displacement";
	if(roll === 35)	return "Cloak of the Bat";
	if(roll === 36)	return "Cube of Force";
	if(roll === 37)	return "Daern's Instant Fortress";
	if(roll === 38)	return "Dagger of Venom";
	if(roll === 39)	return "Dimensional Shackles";
	if(roll === 40)	return "Dragon Slayer";
	if(roll === 41)	return "Elven Chain";
	if(roll === 42)	return "Flame Tongue";
	if(roll === 43)	return "Gem of Seeing";
	if(roll === 44)	return "Giant Slayer";
	if(roll === 45)	return "Clamoured Studded Leather";
	if(roll === 46)	return "Helm of Teleportation";
	if(roll === 47)	return "Horn of Blasting";
	if(roll === 48)	return "Horn of Valhalla (Silver or Brass)";
	if(roll === 49)	return "Instrument of the bards (Canaithmandolin)";
	if(roll === 50)	return "Instrument of the bards (Cii lyre)";
	if(roll === 51)	return "Loun Stone (Awareness)";
	if(roll === 52)	return "Loun Stone (Protection)";
	if(roll === 53)	return "Loun Stone (Reserve)";
	if(roll === 54)	return "Loun Stone (Sustenance)";
	if(roll === 55)	return "Iron Bands of Bilarro";
	if(roll === 56)	return "Armor, +1 Leather";
	if(roll === 57)	return "Armor of Resistance (Leather)";
	if(roll === 58)	return "Mace of Distruption";
	if(roll === 59)	return "Mace of Smiting";
	if(roll === 60)	return "Mace of Terror";
	if(roll === 61)	return "Mantle of Spell Resistance";
	if(roll === 62)	return "Necklace of Prayer Beads";
	if(roll === 63)	return "Periapt of Proof against Poison";
	if(roll === 64)	return "Ring of Animal Influence";
	if(roll === 65)	return "Ring of Evasion";
	if(roll === 66)	return "Ring of Feather Falling";
	if(roll === 67)	return "Ring of Free Action";
	if(roll === 68)	return "Ring of Protection";
	if(roll === 69)	return "Ring of Resistance";
	if(roll === 70)	return "Ring of Spell Storing";
	if(roll === 71)	return "Ring of the Ram";
	if(roll === 72)	return "Ring of X-Ray Vision";
	if(roll === 73)	return "Robe of Eyes";
	if(roll === 74)	return "Rod Rulership";
	if(roll === 75)	return "+2 Rod of the Pact Keeper";
	if(roll === 76)	return "Rope of Entanglement";
	if(roll === 77)	return "Armor, +1 Scale Mail";
	if(roll === 78)	return "Armor of Resitance (Scale Mail)";
	if(roll === 79)	return "+2 Shield";
	if(roll === 80)	return "Shield of Missile Attraction";
	if(roll === 81)	return "Staff of Charming";
	if(roll === 82)	return "Staff of Healing";
	if(roll === 83)	return "Staff of Swarming Insects";
	if(roll === 84) return "Staff of the Woodlands";
	if(roll === 85)	return "Staff of Withering";
	if(roll === 86)	return "Stone of Controlling Earth Elementals";
	if(roll === 87)	return "Sun Blade";
	if(roll === 88)	return "Sword of Life Stealing";
	if(roll === 89)	return "Sword of Wounding";
	if(roll === 90) return "Tentacle Rod";
	if(roll === 91)	return "Vicious Weapon";
	if(roll === 92)	return "Wand of Binding";
	if(roll === 93)	return "Wand of Enemy Detection";
	if(roll === 94)	return "Wand of Fear";
	if(roll === 95)	return "Wand of Fireballs";
	if(roll === 96)	return "Wand of Lightning Bolts";
	if(roll === 97)	return "Wand Paralysis";
	if(roll === 98) return "+2 Wand of the War Mage";
	if(roll === 99) return "Wand of Wonder";
	if(roll === 100) return "Wings of Flying";

};
